#include "memvanta/gguf.hpp"
#include "memvanta/llama_model.hpp"
#include <cassert>
#include <cstdint>
#include <iostream>
#include <random>
#include <string>
#include <vector>

static void roundtrip(memvanta::GgufTokenizer& t,const std::string& s){
    auto ids=t.encode(s,false);auto d=t.decode(ids);if(d!=s){std::cerr<<"roundtrip mismatch bytes="<<s.size()<<" model="<<t.model_type()<<"\n";std::abort();}
}
int main(int argc,char**argv){
    if(argc!=3){std::cerr<<"usage: tokenizer_tests <gpt2.gguf> <sp.gguf>\n";return 2;}
    memvanta::GgufFile gf(argv[1]),sf(argv[2]);memvanta::GgufTokenizer g(gf),sp(sf);
    assert(g.model_type()=="gpt2");assert(sp.model_type()=="llama");
    // Byte completeness, including NUL and malformed UTF-8.
    std::string all;for(int i=0;i<256;++i)all.push_back(static_cast<char>(i));roundtrip(g,all);roundtrip(sp,all);
    roundtrip(g,std::string("\xF0\x28\x8C\x28\0\xFF",6));roundtrip(sp,std::string("\xF0\x28\x8C\x28\0\xFF",6));
    std::mt19937 rng(7);for(int k=0;k<200;++k){std::string s;int n=rng()%129;for(int i=0;i<n;++i)s.push_back(static_cast<char>(rng()%256));roundtrip(g,s);roundtrip(sp,s);}
    // GPT-2 fixture has explicit merges for these.
    auto hi=g.encode("hello world",false);std::vector<int> hi_ref={262,267};assert(hi==hi_ref);
    auto special=g.encode("<|im_start|>user\nhello<|im_end|>",false);assert(!special.empty()&&special.front()==1&&special.back()==2);
    // Exact SentencePiece parity vectors generated by sentencepiece 0.2.1 from the checked-in fixture model.
    struct C{std::string s;std::vector<int> ids;};
    std::vector<C> cs={
      {"Hello world",{259,344,260,263,263,261,259,272,261,269,263,268}},
      {"नमस्ते दुनिया",{259,294,281,347,303,289,259,287,288,294,311,333,274}},
      {"Café naïve résumé",{295,262,267,276,259,265,262,313,293,259,269,276,264,297,276}},
      {"emoji 😀 🚀 ❤️",{259,260,279,261,283,270,259,342,259,343,259,334,341}},
      {"  spaces   and\ttabs",{259,259,259,264,275,298,312,259,259,259,262,265,268,12,306,282,264}},
      {"if (x < 10) { return x * x; }",{259,270,267,259,315,277,259,321,259,319,318,316,259,327,259,305,307,266,299,301,259,317,301,320,259,328}},
    };
    for(const auto&c:cs){auto got=sp.encode(c.s,false);if(got!=c.ids){std::cerr<<"SentencePiece parity mismatch: "<<c.s<<"\n";return 1;}roundtrip(sp,c.s);}
    assert(sp.encode("",false).empty());assert(g.encode("",false).empty());
    std::cout<<"tokenizer tests ok: 2 tokenizer families, 202 byte-fuzz cases, 6 exact SentencePiece parity vectors\n";
}
